/** @module templates/registry */
export type TemplateKind =
  | 'application'
  | 'service'
  | 'plugin'
  | 'connector'
  | 'mission'
  | 'workflow'
  | 'worker';

export interface TemplateFile {
  readonly path: string;
  readonly content: string;
}

export interface TemplateBundle {
  readonly kind: TemplateKind;
  readonly files: readonly TemplateFile[];
}

function pkgName(name: string): string {
  return `@lateen-os/${name}`;
}

export function getTemplate(kind: TemplateKind, name: string): TemplateBundle {
  const packageName = pkgName(name);

  const commonPackageJson = `{
  "name": "${packageName}",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "tsc",
    "typecheck": "tsc --noEmit",
    "test": "vitest run"
  },
  "dependencies": {
    "@lateen-os/sdk": "workspace:*"
  },
  "devDependencies": {
    "@lateen-os/typescript-config": "workspace:*",
    "typescript": "^5.8.3",
    "vitest": "^3.0.5"
  }
}`;

  const commonTsconfig = `{
  "extends": "@lateen-os/typescript-config/node.json",
  "compilerOptions": { "rootDir": "src", "outDir": "dist" },
  "include": ["src"]
}`;

  const manifests: Record<TemplateKind, TemplateFile[]> = {
    plugin: [
      { path: 'package.json', content: commonPackageJson },
      { path: 'tsconfig.json', content: commonTsconfig },
      {
        path: 'src/index.ts',
        content: `import { definePlugin } from '@lateen-os/sdk';

export default definePlugin({
  id: '${name}',
  name: '${name}',
  version: '0.0.1',
  kind: 'package',
  path: 'plugins/${name}',
  permissions: ['publish:events'],
  capabilities: ['${name}'],
});
`,
      },
    ],
    worker: [
      { path: 'package.json', content: commonPackageJson },
      { path: 'tsconfig.json', content: commonTsconfig },
      {
        path: 'src/index.ts',
        content: `import { defineWorker } from '@lateen-os/sdk';

export default defineWorker({
  code: '${name}',
  name: '${name}',
  role: 'specialist',
  skills: [{ id: 'default', name: 'Default Skill', proficiency: '0.8' }],
});
`,
      },
    ],
    connector: [
      { path: 'package.json', content: commonPackageJson },
      { path: 'tsconfig.json', content: commonTsconfig },
      {
        path: 'src/index.ts',
        content: `import { defineConnector } from '@lateen-os/sdk';

export default defineConnector({
  id: '${name}',
  name: '${name}',
  provider: '${name}',
  version: '0.0.1',
  auth: { type: 'api_key', config: { header: 'Authorization' } },
  sync: { mode: 'pull' },
});
`,
      },
    ],
    workflow: [
      { path: 'package.json', content: commonPackageJson },
      { path: 'tsconfig.json', content: commonTsconfig },
      {
        path: 'src/index.ts',
        content: `import { defineWorkflow } from '@lateen-os/sdk';

export default defineWorkflow({
  code: '${name}',
  name: '${name}',
  category: 'custom',
  steps: [{ id: 'start', name: 'Start', type: 'task', order: 0 }],
  triggers: [{ type: 'manual', config: {} }],
});
`,
      },
    ],
    mission: [
      { path: 'package.json', content: commonPackageJson },
      { path: 'tsconfig.json', content: commonTsconfig },
      {
        path: 'src/index.ts',
        content: `import { defineMission } from '@lateen-os/sdk';

export default defineMission({
  code: '${name}',
  title: '${name}',
  description: 'Mission generated by Lateen SDK',
  priority: 'medium',
  stages: [{ id: 'stage-1', name: 'Plan', order: 0, objective: 'Define objective' }],
  outputs: [{ id: 'out-1', name: 'Report', type: 'report' }],
});
`,
      },
    ],
    application: [
      { path: 'package.json', content: commonPackageJson },
      {
        path: 'src/index.ts',
        content: `import { defineApplication } from '@lateen-os/sdk';

export default defineApplication({
  name: '${name}',
  displayName: '${name}',
  port: 3010,
  packageName: '${packageName}',
});
`,
      },
    ],
    service: [
      { path: 'package.json', content: commonPackageJson },
      { path: 'tsconfig.json', content: commonTsconfig },
      {
        path: 'src/index.ts',
        content: `import { defineService } from '@lateen-os/sdk';

export default defineService({
  name: '${name}',
  displayName: '${name}',
  port: 4010,
  packageName: '${packageName}',
  dependencies: ['business-dna-service'],
});
`,
      },
    ],
  };

  return { kind, files: manifests[kind] };
}

export function listTemplates(): readonly TemplateKind[] {
  return ['application', 'service', 'plugin', 'connector', 'mission', 'workflow', 'worker'];
}
