/**
 * Real Documentation engine — the OpenAPI Model and API Documentation
 * Model, both derived purely and deterministically from the Registry
 * (never hand-maintained separately, never generated by a model).
 *
 * @module documentation/engine.impl
 */
import type { Api, ApiVersion, Endpoint, Route } from '../registry/types.js';
import type { RegistryEngine } from '../registry/engine.impl.js';
import type { ApiId, ApiVersionId, OrganizationId } from '../shared/identifiers.js';
import { ApiNotFoundError, ApiVersionNotFoundError } from '../shared/errors.js';
import type { ApiDocumentationModel, OpenApiDocument, OpenApiOperation } from './types.js';

/** Builds a deterministic operationId from method + path (e.g. `GET /crm/customers` -> `get_crm_customers`). */
function operationId(method: string, path: string): string {
  const slug = path
    .split('/')
    .filter(Boolean)
    .join('_')
    .replace(/[^a-zA-Z0-9_]/g, '');
  return `${method.toLowerCase()}_${slug}`;
}

/** Pure builder: a real, minimal OpenAPI 3.0-shaped document from Registry data. */
export function buildOpenApiDocument(api: Api, version: ApiVersion, endpoints: readonly Endpoint[], routesByEndpoint: ReadonlyMap<string, readonly Route[]>): OpenApiDocument {
  const paths: Record<string, Record<string, OpenApiOperation>> = {};
  for (const endpoint of endpoints) {
    const routes = routesByEndpoint.get(endpoint.id) ?? [];
    for (const route of routes) {
      const methodKey = route.method.toLowerCase();
      paths[route.path] = {
        ...(paths[route.path] ?? {}),
        [methodKey]: { operationId: operationId(route.method, route.path), summary: endpoint.description, tags: [endpoint.name] },
      };
    }
  }
  return { openapi: '3.0.3', info: { title: api.name, version: version.version }, paths };
}

/** Pure builder: a human-readable documentation model over the same Registry data. */
export function buildApiDocumentationModel(api: Api, version: ApiVersion, endpoints: readonly Endpoint[], routesByEndpoint: ReadonlyMap<string, readonly Route[]>): ApiDocumentationModel {
  return {
    apiCode: api.code,
    apiName: api.name,
    version: version.version,
    endpoints: endpoints.map((endpoint) => ({
      name: endpoint.name,
      description: endpoint.description,
      routes: (routesByEndpoint.get(endpoint.id) ?? []).map((route) => ({ method: route.method, path: route.path, requiresAuth: route.requiresAuth })),
    })),
  };
}

export interface DocumentationEngine {
  generateOpenApiDocument(organizationId: OrganizationId, apiId: ApiId, versionId: ApiVersionId): Promise<OpenApiDocument>;
  generateApiDocumentation(organizationId: OrganizationId, apiId: ApiId, versionId: ApiVersionId): Promise<ApiDocumentationModel>;
}

/** Creates a real {@link DocumentationEngine}, composed intra-package with the Registry. */
export function createDocumentationEngine(registry: Pick<RegistryEngine, 'getApi' | 'getVersion' | 'listEndpointsForVersion' | 'listRoutesForEndpoint'>): DocumentationEngine {
  async function loadProjection(organizationId: OrganizationId, apiId: ApiId, versionId: ApiVersionId) {
    const api = await registry.getApi(organizationId, apiId);
    if (!api) throw new ApiNotFoundError(apiId);
    const version = await registry.getVersion(organizationId, versionId);
    if (!version) throw new ApiVersionNotFoundError(versionId);
    const endpoints = await registry.listEndpointsForVersion(organizationId, versionId);
    const routesByEndpoint = new Map<string, readonly Route[]>();
    for (const endpoint of endpoints) {
      routesByEndpoint.set(endpoint.id, await registry.listRoutesForEndpoint(organizationId, endpoint.id));
    }
    return { api, version, endpoints, routesByEndpoint };
  }

  return {
    async generateOpenApiDocument(organizationId, apiId, versionId) {
      const { api, version, endpoints, routesByEndpoint } = await loadProjection(organizationId, apiId, versionId);
      return buildOpenApiDocument(api, version, endpoints, routesByEndpoint);
    },

    async generateApiDocumentation(organizationId, apiId, versionId) {
      const { api, version, endpoints, routesByEndpoint } = await loadProjection(organizationId, apiId, versionId);
      return buildApiDocumentationModel(api, version, endpoints, routesByEndpoint);
    },
  };
}
