{{- if .Values.secrets.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "lateen.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lateen.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secrets.externalSecrets.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: {{ include "lateen.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: LATEEN_POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.vault.path }}/postgres
        property: password
    - secretKey: LATEEN_REDIS_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.vault.path }}/redis
        property: password
    - secretKey: LATEEN_MINIO_SECRET_KEY
      remoteRef:
        key: {{ .Values.secrets.vault.path }}/minio
        property: secretKey
    - secretKey: LATEEN_JWT_SECRET
      remoteRef:
        key: {{ .Values.secrets.vault.path }}/identity
        property: jwtSecret
    - secretKey: LATEEN_GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.vault.path }}/grafana
        property: adminPassword
{{- end }}
