{{- if not .Values.secrets.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lateen.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lateen.labels" . | nindent 4 }}
type: Opaque
stringData:
  LATEEN_POSTGRES_USER: lateen
  LATEEN_POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  LATEEN_REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  LATEEN_MINIO_ACCESS_KEY: lateen
  LATEEN_MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | quote }}
  LATEEN_GRAFANA_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword | quote }}
  LATEEN_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
{{- end }}
