/** @module registry/manifest */
import type { PlatformManifest } from './types.js';

/** Canonical Lateen OS platform manifest (Architecture v1.0). */
export const PLATFORM_MANIFEST: PlatformManifest = {
  version: '1.0.0',
  infrastructure: [
    {
      name: 'postgres',
      displayName: 'PostgreSQL',
      package: '',
      path: 'infrastructure/docker',
      port: 5432,
      kind: 'infrastructure',
      dependencies: [],
    },
    {
      name: 'redis',
      displayName: 'Redis',
      package: '',
      path: 'infrastructure/docker',
      port: 6379,
      kind: 'infrastructure',
      dependencies: [],
    },
    {
      name: 'nats',
      displayName: 'NATS',
      package: '',
      path: 'infrastructure/docker',
      port: 4222,
      kind: 'infrastructure',
      dependencies: [],
    },
    {
      name: 'minio',
      displayName: 'MinIO',
      package: '',
      path: 'infrastructure/docker',
      port: 9000,
      kind: 'infrastructure',
      dependencies: [],
    },
    {
      name: 'qdrant',
      displayName: 'Qdrant',
      package: '',
      path: 'infrastructure/docker',
      port: 6333,
      kind: 'infrastructure',
      dependencies: [],
    },
    {
      name: 'prometheus',
      displayName: 'Prometheus',
      package: '',
      path: 'infrastructure/docker',
      port: 9090,
      kind: 'infrastructure',
      dependencies: [],
    },
    {
      name: 'grafana',
      displayName: 'Grafana',
      package: '',
      path: 'infrastructure/docker',
      port: 3000,
      kind: 'infrastructure',
      dependencies: ['prometheus'],
    },
    {
      name: 'otel-collector',
      displayName: 'OpenTelemetry Collector',
      package: '',
      path: 'infrastructure/docker',
      port: 4318,
      kind: 'infrastructure',
      dependencies: [],
    },
  ],
  services: [
    {
      name: 'business-dna-service',
      displayName: 'Business DNA',
      package: '@lateen-os/business-dna-service',
      path: 'services/business-dna-service',
      port: 4001,
      kind: 'backend',
      healthPath: '/health',
      dependencies: [],
      infrastructureDependencies: ['postgres', 'redis', 'nats', 'otel-collector'],
    },
    {
      name: 'product-discovery',
      displayName: 'Product Discovery',
      package: '@lateen-os/product-discovery-service',
      path: 'services/product-discovery',
      port: 4002,
      kind: 'backend',
      healthPath: '/health',
      dependencies: ['business-dna-service'],
      infrastructureDependencies: ['postgres', 'redis', 'nats', 'qdrant', 'otel-collector'],
    },
    {
      name: 'identity-service',
      displayName: 'Identity',
      package: '@lateen-os/identity-service',
      path: 'services/identity-service',
      port: 4003,
      kind: 'backend',
      healthPath: '/health',
      dependencies: ['business-dna-service'],
      infrastructureDependencies: ['postgres', 'redis', 'nats', 'otel-collector'],
    },
    {
      name: 'integration-hub',
      displayName: 'Integration Hub',
      package: '@lateen-os/integration-hub',
      path: 'services/integration-hub',
      port: 4004,
      kind: 'backend',
      healthPath: '/health',
      dependencies: ['business-dna-service', 'identity-service'],
      infrastructureDependencies: ['postgres', 'redis', 'nats', 'minio', 'otel-collector'],
    },
    {
      name: 'mission-scheduler',
      displayName: 'Mission Scheduler',
      package: '@lateen-os/mission-scheduler',
      path: 'services/mission-scheduler',
      port: 4005,
      kind: 'backend',
      healthPath: '/health',
      dependencies: ['business-dna-service', 'product-discovery', 'integration-hub'],
      infrastructureDependencies: ['postgres', 'redis', 'nats', 'otel-collector'],
    },
    {
      name: 'marketplace',
      displayName: 'Marketplace',
      package: '@lateen-os/marketplace-service',
      path: 'services/marketplace',
      port: 4006,
      kind: 'backend',
      healthPath: '/health',
      dependencies: ['identity-service'],
      infrastructureDependencies: ['postgres', 'redis', 'otel-collector'],
    },
    {
      name: 'provisioning',
      displayName: 'Provisioning',
      package: '@lateen-os/provisioning-service',
      path: 'services/provisioning',
      port: 4007,
      kind: 'backend',
      healthPath: '/health',
      dependencies: ['identity-service', 'business-dna-service', 'marketplace'],
      infrastructureDependencies: ['postgres', 'redis', 'otel-collector'],
    },
    {
      name: 'api-gateway',
      displayName: 'API Gateway',
      package: '@lateen-os/api-gateway-service',
      path: 'services/api-gateway',
      port: 4008,
      kind: 'backend',
      healthPath: '/health',
      dependencies: [
        'identity-service',
        'business-dna-service',
        'product-discovery',
        'integration-hub',
        'mission-scheduler',
        'marketplace',
        'provisioning',
      ],
      infrastructureDependencies: ['redis', 'nats', 'otel-collector'],
    },
    {
      name: 'knowledge-platform',
      displayName: 'Knowledge Platform',
      package: '@lateen-os/knowledge-platform-service',
      path: 'services/knowledge-platform',
      port: 4009,
      kind: 'backend',
      healthPath: '/health',
      dependencies: ['business-dna-service', 'identity-service'],
      infrastructureDependencies: ['postgres', 'redis', 'qdrant', 'otel-collector'],
    },
    {
      name: 'search-platform',
      displayName: 'Search Platform',
      package: '@lateen-os/search-platform-service',
      path: 'services/search-platform',
      port: 4010,
      kind: 'backend',
      healthPath: '/health',
      dependencies: ['business-dna-service', 'knowledge-platform', 'marketplace', 'identity-service'],
      infrastructureDependencies: ['redis', 'qdrant', 'otel-collector'],
    },
    {
      name: 'analytics-platform',
      displayName: 'Analytics Platform',
      package: '@lateen-os/analytics-platform-service',
      path: 'services/analytics-platform',
      port: 4011,
      kind: 'backend',
      healthPath: '/health',
      dependencies: ['business-dna-service', 'search-platform', 'knowledge-platform', 'marketplace', 'identity-service'],
      infrastructureDependencies: ['redis', 'otel-collector'],
    },
    {
      name: 'cloud-control-plane',
      displayName: 'Cloud Control Plane',
      package: '@lateen-os/cloud-control-plane-service',
      path: 'services/cloud-control-plane',
      port: 4012,
      kind: 'backend',
      healthPath: '/health',
      dependencies: ['provisioning', 'identity-service', 'marketplace', 'analytics-platform'],
      infrastructureDependencies: ['postgres', 'redis', 'otel-collector'],
    },
  ],
  applications: [
    {
      name: 'ai-product-manager',
      displayName: 'AI Product Manager',
      package: '@lateen-os/ai-product-manager',
      path: 'apps/ai-product-manager',
      port: 3000,
    },
    {
      name: 'business-dna-studio',
      displayName: 'Business DNA Studio',
      package: '@lateen-os/business-dna-studio',
      path: 'apps/business-dna-studio',
      port: 3001,
    },
    {
      name: 'ceo-cockpit',
      displayName: 'CEO Cockpit',
      package: '@lateen-os/ceo-cockpit',
      path: 'apps/ceo-cockpit',
      port: 3002,
    },
    {
      name: 'customer-portal',
      displayName: 'Customer Portal',
      package: '@lateen-os/customer-portal',
      path: 'apps/customer-portal',
      port: 3003,
    },
    {
      name: 'lateen-assistant',
      displayName: 'Lateen Assistant',
      package: '@lateen-os/lateen-assistant',
      path: 'apps/lateen-assistant',
      port: 3004,
    },
    {
      name: 'marketplace',
      displayName: 'Marketplace',
      package: '@lateen-os/marketplace',
      path: 'apps/marketplace',
      port: 3005,
    },
    {
      name: 'setup-wizard',
      displayName: 'Setup Wizard',
      package: '@lateen-os/setup-wizard',
      path: 'apps/setup-wizard',
      port: 3006,
    },
    {
      name: 'admin-gateway',
      displayName: 'Admin Gateway',
      package: '@lateen-os/admin-gateway',
      path: 'apps/admin-gateway',
      port: 3007,
    },
    {
      name: 'search-center',
      displayName: 'Search Center',
      package: '@lateen-os/search-center',
      path: 'apps/search-center',
      port: 3008,
    },
    {
      name: 'ai-studio',
      displayName: 'AI Studio',
      package: '@lateen-os/ai-studio',
      path: 'apps/ai-studio',
      port: 3009,
    },
    {
      name: 'automation-studio',
      displayName: 'Automation Studio',
      package: '@lateen-os/automation-studio',
      path: 'apps/automation-studio',
      port: 3010,
    },
    {
      name: 'analytics-center',
      displayName: 'Analytics Center',
      package: '@lateen-os/analytics-center',
      path: 'apps/analytics-center',
      port: 3011,
    },
    {
      name: 'cloud-console',
      displayName: 'Cloud Console',
      package: '@lateen-os/cloud-console',
      path: 'apps/cloud-console',
      port: 3012,
    },
  ],
};
